USE MASTER

GO

CREATE DATABASE ITLAB_TESTEDB

GO

USE ITLAB_TESTEDB

GO

CREATE TABLE [dbo].[tbPRODUTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [nvarchar](50) NOT NULL,
	[IDTIPO] [int] NOT NULL,
	[DTFABRICACAO] [datetime] NOT NULL,
	[VALOR] [money] NOT NULL,
	[DATACADASTRO] [datetime] NOT NULL,
	[DISPONIVEL] [bit] NOT NULL,
	[NORTE] [char](1) NULL,
	[SUL] [char](1) NULL,
	[LESTE] [char](1) NULL,
	[OESTE] [char](1) NULL,
 CONSTRAINT [PK_IDPRODUTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[tbTIPO](
ID INT IDENTITY(1,1) NOT NULL,
NOME NVARCHAR(30) NOT NULL,
DESCRICAO NVARCHAR(50) NULL,
CONSTRAINT [PK_IDTIPO] PRIMARY KEY CLUSTERED
(
   [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]

GO







