USE MASTER

GO

CREATE DATABASE ITLAB_TESTEDB

GO

USE ITLAB_TESTEDB

GO

CREATE TABLE tbPRODUTO(
ID INT IDENTITY(1,1) NOT NULL,
NOME NVARCHAR(50) NOT NULL,
IDTIPO INT NOT NULL,
DTFABRICACAO DATETIME NOT NULL,
VALOR FLOAT,
DATACADASTRO DATETIME,
CONSTRAINT [PK_IDPRODUTO] PRIMARY KEY CLUSTERED
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]

GO

CREATE TABLE tbTIPO(
ID INT IDENTITY(1,1) NOT NULL,
NOME NVARCHAR(30) NOT NULL,
DESCRICAO NVARCHAR(50) NULL,
CONSTRAINT [PK_IDTIPO] PRIMARY KEY CLUSTERED
(
   [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]

GO







